### PR TITLE
Adds MaterialReactTable export

### PR DESCRIPTION
**Pull request by kaveon14**
I'm currently working on upgrading WUI in Sponsors and this export was forgotten in this PR: https://github.com/MetLifeLegalPlans/wui/pull/81

### CODE REVIEW

**Comment by kaveon14** [comment]
Do I need to update the version in `package.json`?

**Comment by kaveon14** [comment]
MRT is used in the `EditEnrollmentFileTable`. Basically ties into this [comment](https://github.com/MetLifeLegalPlans/wui/pull/81#issuecomment-1946704315)

**Comment by kelarcrisp** [comment]
> MRT is used in the `EditEnrollmentFileTable`. Basically ties into this [comment](https://github.com/MetLifeLegalPlans/wui/pull/81#issuecomment-1946704315)

ohh, I see. ugh, sorry for not understanding the issue Cameron issued earlier with your first pr, but I think what we should do is just update the `editEnrollmentFileTable ` 

> MRT is used in the `EditEnrollmentFileTable`. Basically ties into this [comment](https://github.com/MetLifeLegalPlans/wui/pull/81#issuecomment-1946704315)

oh, I see. ugh, I hate exporting both of these just to accommodate for one use case, but I guess it's fine for now. can we please create an issue explaining why we're exporting both `useMaterialReactTable` and `MaterialReactTable`? I think ideally we update the `CustomTable` and `CustomTableWithActions` in wui to v2 of MRT api (where we use the hook) so the user's API (sponsors,attorneys) stays the same. it would be AMAZING if you could take this on, but an issue seems OK for now if you can't

**Comment by kelarcrisp** [comment]
and yeah, I think bumping to 5.1.1 would be best

**Comment by kaveon14** [comment]
Yeah I can create issue to figure out why those hooks are needed in `EditEnrollmentFileTable`. And I can also get MRT upgraded to V2. I should be able to start on those issues next week.

**Review by kelarcrisp — APPROVED** [review]

**Pull request merged**
